import { drizzle } from "drizzle-orm/postgres-js";
import { migrate } from "drizzle-orm/postgres-js/migrator";
import postgres from "postgres";

/**
 * Runs DB migrations on startup.
 * Uses drizzle-orm migrator if migrations folder exists (generated by drizzle-kit generate),
 * otherwise falls back to CREATE TABLE IF NOT EXISTS for each table in the schema.
 */
export async function runMigrations(): Promise<void> {
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL is not set");

  // Separate connection for migrations (max 1 connection, no idle timeout)
  const migrationClient = postgres(url, { max: 1 });

  try {
    console.log("[migrate] Running database migrations...");

    await migrationClient`
      CREATE TABLE IF NOT EXISTS tracks (
        id        SERIAL PRIMARY KEY,
        name      TEXT NOT NULL,
        country   TEXT NOT NULL,
        length_km REAL NOT NULL,
        turns     INTEGER NOT NULL,
        layout    TEXT NOT NULL
      )
    `;

    await migrationClient`
      CREATE TABLE IF NOT EXISTS drivers (
        id      SERIAL PRIMARY KEY,
        name    TEXT NOT NULL,
        team    TEXT NOT NULL,
        country TEXT NOT NULL
      )
    `;

    await migrationClient`
      CREATE TABLE IF NOT EXISTS sessions (
        id                    SERIAL PRIMARY KEY,
        track_id              INTEGER NOT NULL,
        event                 TEXT NOT NULL,
        session_type          TEXT NOT NULL,
        venue                 TEXT NOT NULL,
        course                TEXT,
        track_length_m        REAL,
        game_version          TEXT,
        date_time             TEXT NOT NULL,
        date_time_unix        BIGINT,
        file_name             TEXT NOT NULL,
        setting               TEXT,
        driver_count          INTEGER NOT NULL,
        lap_count             INTEGER NOT NULL,
        race_laps             INTEGER,
        race_time_min         INTEGER,
        mech_fail_rate        INTEGER,
        damage_mult           INTEGER,
        fuel_mult             REAL,
        tire_mult             REAL,
        vehicles_allowed      TEXT,
        parc_ferme            INTEGER,
        fixed_setups          INTEGER,
        free_settings         INTEGER,
        fixed_upgrades        INTEGER,
        tire_warmers          INTEGER,
        dedicated             INTEGER,
        session_duration_min  INTEGER,
        session_max_laps      INTEGER,
        most_laps_completed   INTEGER
      )
    `;

    await migrationClient`
      CREATE TABLE IF NOT EXISTS lap_times (
        id          SERIAL PRIMARY KEY,
        track_id    INTEGER NOT NULL,
        driver_id   INTEGER NOT NULL,
        car_class   TEXT NOT NULL,
        car         TEXT NOT NULL,
        lap_ms      INTEGER NOT NULL,
        sector1_ms  INTEGER NOT NULL,
        sector2_ms  INTEGER NOT NULL,
        sector3_ms  INTEGER NOT NULL,
        conditions  TEXT NOT NULL,
        tyre        TEXT NOT NULL,
        date        TEXT NOT NULL,
        source      TEXT NOT NULL DEFAULT 'demo',
        session_id  INTEGER
      )
    `;

    await migrationClient`
      CREATE TABLE IF NOT EXISTS import_jobs (
        id                  TEXT PRIMARY KEY,
        file_hash           TEXT NOT NULL UNIQUE,
        file_name           TEXT NOT NULL,
        status              TEXT NOT NULL DEFAULT 'queued',
        session_id          INTEGER,
        total_laps          INTEGER,
        valid_laps          INTEGER,
        error_laps          INTEGER,
        error               TEXT,
        log_format_version  TEXT,
        created_at          BIGINT NOT NULL,
        finished_at         BIGINT
      )
    `;

    await migrationClient`
      CREATE TABLE IF NOT EXISTS import_errors (
        id              SERIAL PRIMARY KEY,
        import_job_id   TEXT NOT NULL,
        raw_payload     TEXT NOT NULL,
        error_code      TEXT NOT NULL,
        error_message   TEXT NOT NULL,
        occurred_at     BIGINT NOT NULL
      )
    `;

    await migrationClient`
      CREATE TABLE IF NOT EXISTS session_results (
        id                        SERIAL PRIMARY KEY,
        session_id                INTEGER NOT NULL,
        driver_id                 INTEGER NOT NULL,
        is_player                 INTEGER NOT NULL DEFAULT 0,
        position                  INTEGER NOT NULL,
        class_position            INTEGER NOT NULL,
        lap_rank_including_discos INTEGER,
        car_class                 TEXT NOT NULL,
        car                       TEXT NOT NULL,
        car_type                  TEXT,
        team                      TEXT NOT NULL,
        car_number                TEXT,
        veh_file                  TEXT,
        veh_name                  TEXT,
        category                  TEXT,
        laps                      INTEGER NOT NULL,
        pitstops                  INTEGER NOT NULL,
        best_lap_ms               INTEGER,
        finish_status             TEXT,
        control_and_aids          TEXT,
        connected                 INTEGER
      )
    `;

    await migrationClient`
      CREATE TABLE IF NOT EXISTS session_laps (
        id                      SERIAL PRIMARY KEY,
        session_result_id       INTEGER NOT NULL,
        session_id              INTEGER NOT NULL,
        driver_id               INTEGER NOT NULL,
        lap_num                 INTEGER NOT NULL,
        position                INTEGER,
        lap_time_ms             REAL,
        elapsed_time_sec        REAL,
        sector1_ms              REAL,
        sector2_ms              REAL,
        sector3_ms              REAL,
        top_speed_kph           REAL,
        fuel_level              REAL,
        fuel_used               REAL,
        vehicle_condition       REAL,
        vehicle_condition_used  REAL,
        tyre_fl_condition       REAL,
        tyre_fr_condition       REAL,
        tyre_rl_condition       REAL,
        tyre_rr_condition       REAL,
        front_compound          TEXT,
        rear_compound           TEXT,
        tyre_fl                 TEXT,
        tyre_fr                 TEXT,
        tyre_rl                 TEXT,
        tyre_rr                 TEXT,
        is_pit_lap              INTEGER NOT NULL DEFAULT 0
      )
    `;

    await migrationClient`
      CREATE TABLE IF NOT EXISTS session_incidents (
        id                SERIAL PRIMARY KEY,
        session_id        INTEGER NOT NULL,
        driver_id         INTEGER NOT NULL,
        target_driver_id  INTEGER,
        elapsed_time_sec  REAL NOT NULL,
        severity          REAL NOT NULL,
        is_immovable      INTEGER NOT NULL DEFAULT 0
      )
    `;

    await migrationClient`
      CREATE TABLE IF NOT EXISTS session_sector_bests (
        id                SERIAL PRIMARY KEY,
        session_id        INTEGER NOT NULL,
        driver_id         INTEGER NOT NULL,
        car_class         TEXT NOT NULL,
        sector            INTEGER NOT NULL,
        elapsed_time_sec  REAL NOT NULL,
        lap_num           INTEGER
      )
    `;

    await migrationClient`
      CREATE TABLE IF NOT EXISTS session_track_limits (
        id                SERIAL PRIMARY KEY,
        session_id        INTEGER NOT NULL,
        driver_id         INTEGER NOT NULL,
        lap_num           INTEGER NOT NULL,
        elapsed_time_sec  REAL NOT NULL,
        warning_points    INTEGER,
        current_points    INTEGER,
        resolution        INTEGER,
        decision          TEXT
      )
    `;

    console.log("[migrate] All tables are up to date.");
  } finally {
    await migrationClient.end();
  }
}
